(function(global){
  const CLASS_DATABASE = [
    { name:"Knight", stats:{STR:8,DEX:4,CON:8,INT:3,WIS:4,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:35,EP:1,AP:2,MOV:3}, startingSkills:["Taunt","Shield Wall","Parry"] },
    { name:"Magician", stats:{STR:3,DEX:5,CON:4,INT:8,WIS:6,CHA:4}, attunement:{FAE:6,DREAM:5}, resources:{HP:22,EP:1,AP:2,MOV:4}, startingSkills:["Arcane Bolt","Elemental Blast","Ward"] },
    { name:"Warlock", stats:{STR:3,DEX:4,CON:4,INT:7,WIS:4,CHA:4}, attunement:{FAE:7,DREAM:7}, resources:{HP:20,EP:1,AP:2,MOV:4}, startingSkills:["Life Leech","Hex","Dark Pact"] },
    { name:"Archer", stats:{STR:4,DEX:8,CON:5,INT:4,WIS:3,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:24,EP:1,AP:2,MOV:6}, startingSkills:["Snipe","Volley","Pinning Shot"] },
    { name:"Scout", stats:{STR:4,DEX:7,CON:4,INT:4,WIS:3,CHA:6}, attunement:{FAE:0,DREAM:0}, resources:{HP:22,EP:1,AP:2,MOV:7}, startingSkills:["Slipstream Step","Trap Sense","Ambush"] },
    { name:"Cleric", stats:{STR:3,DEX:4,CON:5,INT:5,WIS:8,CHA:5}, attunement:{FAE:0,DREAM:2}, resources:{HP:26,EP:1,AP:2,MOV:4}, startingSkills:["Heal","Turn Undead","Ward Chant"] },
    { name:"Druid", stats:{STR:3,DEX:4,CON:5,INT:6,WIS:7,CHA:4}, attunement:{FAE:6,DREAM:3}, resources:{HP:25,EP:1,AP:2,MOV:5}, startingSkills:["Shapeshift","Entangle","Restorative Wind"] },
    { name:"Fighter", stats:{STR:7,DEX:6,CON:6,INT:4,WIS:4,CHA:4}, attunement:{FAE:0,DREAM:0}, resources:{HP:30,EP:1,AP:2,MOV:5}, startingSkills:["Power Strike","Counter","Weapon Stance"] },
    { name:"Rogue", stats:{STR:5,DEX:8,CON:4,INT:4,WIS:3,CHA:6}, attunement:{FAE:0,DREAM:0}, resources:{HP:22,EP:1,AP:2,MOV:6}, startingSkills:["Backstab","Poisoned Dagger","Camouflage"] },
    { name:"Monk", stats:{STR:6,DEX:7,CON:5,INT:4,WIS:6,CHA:4}, attunement:{FAE:0,DREAM:2}, resources:{HP:27,EP:1,AP:2,MOV:6}, startingSkills:["Counterstrike","Chi Strike","Palm of Flame"] },
    { name:"Shaman", stats:{STR:4,DEX:4,CON:5,INT:5,WIS:7,CHA:4}, attunement:{FAE:2,DREAM:6}, resources:{HP:25,EP:1,AP:2,MOV:4}, startingSkills:["Totem Call","Spirit Bind","Stormsong"] },
    { name:"Warden", stats:{STR:7,DEX:3,CON:9,INT:3,WIS:5,CHA:4}, attunement:{FAE:0,DREAM:0}, resources:{HP:38,EP:1,AP:2,MOV:3}, startingSkills:["Zone Control","Shield Slam","Fortify"] },
    { name:"Engineer", stats:{STR:4,DEX:4,CON:6,INT:7,WIS:5,CHA:3}, attunement:{FAE:0,DREAM:0}, resources:{HP:28,EP:1,AP:2,MOV:4}, startingSkills:["Deploy Turret","Trap","Salvage Duty"] },
    { name:"Necromancer", stats:{STR:3,DEX:4,CON:4,INT:8,WIS:4,CHA:3}, attunement:{FAE:0,DREAM:8}, resources:{HP:22,EP:1,AP:2,MOV:4}, startingSkills:["Raise Skeleton","Fear","Soul Drain"] },
    { name:"Reaper", stats:{STR:6,DEX:7,CON:4,INT:5,WIS:4,CHA:3}, attunement:{FAE:0,DREAM:6}, resources:{HP:24,EP:1,AP:2,MOV:6}, startingSkills:["Shadow Strike","Harvest Soul","Fade Step"] },
    { name:"Symphonist", stats:{STR:4,DEX:5,CON:5,INT:6,WIS:5,CHA:8}, attunement:{FAE:4,DREAM:4}, resources:{HP:26,EP:1,AP:2,MOV:5}, startingSkills:["Harmony Strike","Discordant Wave","Resonance"] },
    { name:"Gunslinger", stats:{STR:5,DEX:8,CON:4,INT:4,WIS:3,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:22,EP:1,AP:2,MOV:6}, startingSkills:["Trick Shot","Ricochet","Quickdraw"] },
    { name:"Ninja", stats:{STR:5,DEX:9,CON:3,INT:4,WIS:3,CHA:4}, attunement:{FAE:4,DREAM:4}, resources:{HP:20,EP:1,AP:2,MOV:7}, startingSkills:["Smoke Vanish","Kunai Throw","Shadowstep"] },
    { name:"Samurai", stats:{STR:7,DEX:6,CON:6,INT:4,WIS:6,CHA:4}, attunement:{FAE:0,DREAM:2}, resources:{HP:30,EP:1,AP:2,MOV:4}, startingSkills:["Iaido Strike","Discipline Stance","Resolve"] },
    { name:"Pirate", stats:{STR:7,DEX:6,CON:5,INT:4,WIS:3,CHA:6}, attunement:{FAE:0,DREAM:0}, resources:{HP:28,EP:1,AP:2,MOV:5}, startingSkills:["Disarm","Broadside","Rally or Rum"] },
    { name:"Brigadier", stats:{STR:6,DEX:5,CON:8,INT:4,WIS:4,CHA:7}, attunement:{FAE:0,DREAM:0}, resources:{HP:34,EP:1,AP:2,MOV:4}, startingSkills:["Charge","Formation Guard","Tactical Rally"] },
    { name:"Privateer", stats:{STR:6,DEX:7,CON:5,INT:4,WIS:4,CHA:6}, attunement:{FAE:0,DREAM:0}, resources:{HP:27,EP:1,AP:2,MOV:5}, startingSkills:["Boarding Action","Morale Breaker","Naval Tactics"] },
    { name:"Spellblade", stats:{STR:6,DEX:6,CON:5,INT:7,WIS:4,CHA:4}, attunement:{FAE:5,DREAM:2}, resources:{HP:28,EP:1,AP:2,MOV:5}, startingSkills:["Flameblade","Arcane Slash","Elemental Guard"] },
    { name:"Skaldblade", stats:{STR:7,DEX:6,CON:6,INT:4,WIS:4,CHA:7}, attunement:{FAE:0,DREAM:0}, resources:{HP:30,EP:1,AP:2,MOV:5}, startingSkills:["Tempo Strike","Chant Rally","Momentum Slash"] },
    { name:"Essentier", stats:{STR:5,DEX:5,CON:7,INT:7,WIS:4,CHA:3}, attunement:{FAE:0,DREAM:0}, resources:{HP:32,EP:1,AP:2,MOV:4}, startingSkills:["Alchemy Strike","Scrap Bomb","Essence Burn"] },
    { name:"Shadowguard", stats:{STR:6,DEX:7,CON:6,INT:4,WIS:4,CHA:4}, attunement:{FAE:0,DREAM:3}, resources:{HP:30,EP:1,AP:2,MOV:5}, startingSkills:["Swap Places","Intercept","Silent Guard"] },
    { name:"Torchbearer", stats:{STR:7,DEX:5,CON:6,INT:4,WIS:4,CHA:4}, attunement:{FAE:6,DREAM:0}, resources:{HP:29,EP:1,AP:2,MOV:5}, startingSkills:["Ignite","Reveal Shadows","Firebrand"] },
    { name:"Swashbuckler", stats:{STR:6,DEX:8,CON:5,INT:4,WIS:3,CHA:6}, attunement:{FAE:0,DREAM:0}, resources:{HP:28,EP:1,AP:2,MOV:6}, startingSkills:["Taunt","Parry-Riposte","Showboat"] },
    { name:"Riftwarden", stats:{STR:5,DEX:5,CON:6,INT:6,WIS:7,CHA:4}, attunement:{FAE:0,DREAM:8}, resources:{HP:28,EP:1,AP:2,MOV:5}, startingSkills:["Teleport Rift","Banish","Anchor Zone"] },
    { name:"Bard", stats:{STR:3,DEX:4,CON:5,INT:5,WIS:5,CHA:9}, attunement:{FAE:0,DREAM:3}, resources:{HP:26,EP:1,AP:2,MOV:5}, startingSkills:["Inspiring Ballad","Cleansing Chorus","Battle Hymn"] },
    { name:"Dancer", stats:{STR:3,DEX:8,CON:4,INT:4,WIS:5,CHA:7}, attunement:{FAE:0,DREAM:2}, resources:{HP:22,EP:1,AP:2,MOV:7}, startingSkills:["Mirrorstep","Dodge Dance","Action Gift"] },
    { name:"Diplomat", stats:{STR:3,DEX:4,CON:4,INT:5,WIS:6,CHA:9}, attunement:{FAE:0,DREAM:2}, resources:{HP:22,EP:1,AP:2,MOV:5}, startingSkills:["Parley","Influence Morale","Truce"] },
    { name:"Commander", stats:{STR:5,DEX:5,CON:7,INT:4,WIS:5,CHA:8}, attunement:{FAE:0,DREAM:0}, resources:{HP:32,EP:1,AP:2,MOV:4}, startingSkills:["Command Authority","Deploy Orders","Rallying Cry"] },
    { name:"Quartermaster", stats:{STR:4,DEX:4,CON:6,INT:7,WIS:7,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:30,EP:1,AP:2,MOV:4}, startingSkills:["Supply Drop","Stamina Boost","Resupply"] },
    { name:"Librarian", stats:{STR:3,DEX:4,CON:5,INT:9,WIS:6,CHA:4}, attunement:{FAE:0,DREAM:2}, resources:{HP:26,EP:1,AP:2,MOV:4}, startingSkills:["Reveal Weakness","Lore Archive","Battle Scan"] },
    { name:"Beastmaster", stats:{STR:5,DEX:5,CON:6,INT:4,WIS:6,CHA:6}, attunement:{FAE:0,DREAM:0}, resources:{HP:30,EP:1,AP:2,MOV:5}, startingSkills:["Summon Beast","Command Beast","Wild Roar"] },
    { name:"Herbalist", stats:{STR:4,DEX:4,CON:5,INT:6,WIS:8,CHA:4}, attunement:{FAE:0,DREAM:0}, resources:{HP:26,EP:1,AP:2,MOV:5}, startingSkills:["Herbal Remedy","Poison Bomb","Antidote"] },
    { name:"Oracle", stats:{STR:3,DEX:4,CON:4,INT:6,WIS:9,CHA:5}, attunement:{FAE:2,DREAM:8}, resources:{HP:22,EP:1,AP:2,MOV:4}, startingSkills:["Prophecy","Veil Sight","Fate Bind"] },
    { name:"Chaplain", stats:{STR:4,DEX:4,CON:6,INT:5,WIS:8,CHA:6}, attunement:{FAE:0,DREAM:0}, resources:{HP:30,EP:1,AP:2,MOV:4}, startingSkills:["Sacred Ward","Blessing","Inspire Courage"] },
    { name:"Archivist", stats:{STR:3,DEX:4,CON:5,INT:8,WIS:6,CHA:5}, attunement:{FAE:0,DREAM:2}, resources:{HP:26,EP:1,AP:2,MOV:4}, startingSkills:["Record Action","Shift Turn Order","Knowledge Recall"] },
    { name:"Soothsayer", stats:{STR:3,DEX:4,CON:4,INT:6,WIS:8,CHA:5}, attunement:{FAE:0,DREAM:8}, resources:{HP:22,EP:1,AP:2,MOV:4}, startingSkills:["Omen","Redirect Curse","Hex Prolong"] },
    { name:"Caretaker", stats:{STR:4,DEX:4,CON:6,INT:5,WIS:8,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:30,EP:1,AP:2,MOV:4}, startingSkills:["Stabilize","Nurture","Revive"] },
    { name:"Chanter", stats:{STR:4,DEX:5,CON:5,INT:6,WIS:7,CHA:7}, attunement:{FAE:0,DREAM:2}, resources:{HP:26,EP:1,AP:2,MOV:5}, startingSkills:["Aura Chant","Sustained Hymn","Passive Blessing"] },
    { name:"Merchant", stats:{STR:3,DEX:4,CON:5,INT:6,WIS:5,CHA:9}, attunement:{FAE:0,DREAM:0}, resources:{HP:26,EP:1,AP:2,MOV:5}, startingSkills:["Bargain","Market Manipulation","Greed is Good"] },
    { name:"Cartographer", stats:{STR:3,DEX:5,CON:5,INT:7,WIS:7,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:27,EP:1,AP:2,MOV:5}, startingSkills:["Reveal Map","Alter Terrain","Pathfinder"] },
    { name:"Witch", stats:{STR:3,DEX:5,CON:4,INT:6,WIS:5,CHA:5}, attunement:{FAE:8,DREAM:7}, resources:{HP:22,EP:1,AP:2,MOV:5}, startingSkills:["Hex","Illusion","Charm"] },
    { name:"Runesmith", stats:{STR:4,DEX:4,CON:5,INT:8,WIS:7,CHA:4}, attunement:{FAE:0,DREAM:0}, resources:{HP:26,EP:1,AP:2,MOV:4}, startingSkills:["Rune Ward","Explosive Glyph","Runic Enhancement"] },
    { name:"Tailor", stats:{STR:3,DEX:7,CON:4,INT:6,WIS:5,CHA:6}, attunement:{FAE:6,DREAM:3}, resources:{HP:22,EP:1,AP:2,MOV:6}, startingSkills:["Illusion Stitch","Armor Weave","Disguise"] },
    { name:"Navigator", stats:{STR:4,DEX:6,CON:5,INT:5,WIS:7,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:27,EP:1,AP:2,MOV:6}, startingSkills:["Pathfinder","Sea Legs","Sky Mark"] },
    { name:"Folk Companion", stats:{STR:4,DEX:5,CON:5,INT:4,WIS:4,CHA:4}, attunement:{FAE:0,DREAM:0}, resources:{HP:24,EP:1,AP:2,MOV:6}, startingSkills:["Trickster Fox","Owl Sight","Bear Roar"] },
    { name:"Artificer", stats:{STR:4,DEX:5,CON:6,INT:8,WIS:5,CHA:4}, attunement:{FAE:0,DREAM:0}, resources:{HP:28,EP:1,AP:2,MOV:4}, startingSkills:["Gadget Deploy","Overclock","Repair"] },
    { name:"Chronicler", stats:{STR:3,DEX:4,CON:5,INT:6,WIS:6,CHA:7}, attunement:{FAE:0,DREAM:2}, resources:{HP:26,EP:1,AP:2,MOV:5}, startingSkills:["Record Heroics","Echo of Past","Tale Boost"] },
    { name:"Trapper", stats:{STR:4,DEX:7,CON:5,INT:5,WIS:5,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:27,EP:1,AP:2,MOV:6}, startingSkills:["Snare","Pitfall","Net Toss"] },
    { name:"Tinker", stats:{STR:3,DEX:6,CON:5,INT:7,WIS:5,CHA:5}, attunement:{FAE:0,DREAM:0}, resources:{HP:27,EP:1,AP:2,MOV:5}, startingSkills:["Build Ladder","Bridge","Quick Tool"] },
    { name:"Courier", stats:{STR:3,DEX:7,CON:4,INT:5,WIS:5,CHA:7}, attunement:{FAE:0,DREAM:0}, resources:{HP:24,EP:1,AP:2,MOV:7}, startingSkills:["Swap Positions","Item Transfer","Messenger"] },
    { name:"Scrapper", stats:{STR:6,DEX:5,CON:7,INT:4,WIS:4,CHA:4}, attunement:{FAE:0,DREAM:0}, resources:{HP:32,EP:1,AP:2,MOV:5}, startingSkills:["Scavenge","Improvised Weapon","Salvage Armor"] },
    { name:"Signalist", stats:{STR:3,DEX:5,CON:5,INT:6,WIS:5,CHA:8}, attunement:{FAE:0,DREAM:0}, resources:{HP:27,EP:1,AP:2,MOV:5}, startingSkills:["Flare","Flag Orders","Reveal Zone"] },
  ];

  const SKILL_BEHAVIORS = {
    "Taunt":"buffSelfGuard",
    "Shield Wall":"buffSelfGuard",
    "Parry":"buffSelfGuard",
    "Arcane Bolt":"attackRanged",
    "Elemental Blast":"attackRanged",
    "Ward":"buffAllyGuard",
    "Life Leech":"attackLifeSteal",
    "Hex":"attackRanged",
    "Dark Pact":"buffSelfInspire",
    "Snipe":"attackRanged",
    "Volley":"attackRanged",
    "Pinning Shot":"attackRangedRoot",
    "Slipstream Step":"buffSelfInspire",
    "Trap Sense":"buffSelfGuard",
    "Ambush":"attackMelee",
    "Heal":"heal",
    "Turn Undead":"attackRanged",
    "Ward Chant":"buffAllyGuard",
    "Shapeshift":"buffSelfInspire",
    "Entangle":"root",
    "Restorative Wind":"heal",
    "Counter":"buffSelfGuard",
    "Weapon Stance":"buffSelfInspire",
    "Backstab":"attackMelee",
    "Poisoned Dagger":"attackMeleeBleed",
    "Camouflage":"buffSelfGuard",
    "Counterstrike":"buffSelfGuard",
    "Chi Strike":"attackMelee",
    "Palm of Flame":"attackMelee",
    "Totem Call":"buffAllyInspire",
    "Spirit Bind":"attackLifeSteal",
    "Stormsong":"attackRanged",
    "Zone Control":"buffSelfGuard",
    "Shield Slam":"attackMelee",
    "Fortify":"buffAllyGuard",
    "Deploy Turret":"attackRanged",
    "Trap":"root",
    "Salvage Duty":"heal",
    "Raise Skeleton":"attackRanged",
    "Fear":"attackRanged",
    "Soul Drain":"attackLifeSteal",
    "Shadow Strike":"attackMelee",
    "Harvest Soul":"attackLifeSteal",
    "Fade Step":"buffSelfInspire",
    "Harmony Strike":"attackMelee",
    "Discordant Wave":"attackRanged",
    "Resonance":"heal",
    "Trick Shot":"attackRanged",
    "Ricochet":"attackRanged",
    "Quickdraw":"attackRanged",
    "Smoke Vanish":"buffSelfGuard",
    "Kunai Throw":"attackRanged",
    "Shadowstep":"buffSelfInspire",
    "Iaido Strike":"attackMelee",
    "Discipline Stance":"buffSelfGuard",
    "Resolve":"buffSelfGuard",
    "Disarm":"attackMelee",
    "Broadside":"attackRanged",
    "Rally or Rum":"heal",
    "Charge":"attackMelee",
    "Formation Guard":"buffAllyGuard",
    "Tactical Rally":"buffAllyInspire",
    "Boarding Action":"attackMelee",
    "Morale Breaker":"attackMelee",
    "Naval Tactics":"buffAllyInspire",
    "Flameblade":"attackMelee",
    "Arcane Slash":"attackMelee",
    "Elemental Guard":"buffSelfGuard",
    "Tempo Strike":"attackMelee",
    "Chant Rally":"buffAllyInspire",
    "Momentum Slash":"attackMelee",
    "Alchemy Strike":"attackMelee",
    "Scrap Bomb":"attackRanged",
    "Essence Burn":"attackRanged",
    "Swap Places":"swap",
    "Intercept":"buffAllyGuard",
    "Silent Guard":"buffSelfGuard",
    "Ignite":"attackRanged",
    "Reveal Shadows":"buffAllyGuard",
    "Firebrand":"attackMelee",
    "Parry-Riposte":"attackMelee",
    "Showboat":"buffSelfInspire",
    "Teleport Rift":"buffSelfInspire",
    "Banish":"attackRanged",
    "Anchor Zone":"buffAllyGuard",
    "Inspiring Ballad":"buffAllyInspire",
    "Cleansing Chorus":"heal",
    "Battle Hymn":"buffAllyInspire",
    "Mirrorstep":"buffSelfInspire",
    "Dodge Dance":"buffSelfGuard",
    "Action Gift":"buffAllyInspire",
    "Parley":"buffAllyGuard",
    "Influence Morale":"buffAllyInspire",
    "Truce":"buffAllyGuard",
    "Command Authority":"buffAllyInspire",
    "Deploy Orders":"buffAllyInspire",
    "Rallying Cry":"buffAllyInspire",
    "Supply Drop":"heal",
    "Stamina Boost":"buffAllyInspire",
    "Resupply":"heal",
    "Reveal Weakness":"attackRanged",
    "Lore Archive":"buffSelfInspire",
    "Battle Scan":"buffAllyGuard",
    "Summon Beast":"attackMelee",
    "Command Beast":"buffAllyInspire",
    "Wild Roar":"attackRanged",
    "Herbal Remedy":"heal",
    "Poison Bomb":"attackRanged",
    "Antidote":"heal",
    "Prophecy":"buffAllyInspire",
    "Veil Sight":"buffSelfGuard",
    "Fate Bind":"attackRanged",
    "Sacred Ward":"buffAllyGuard",
    "Blessing":"buffAllyGuard",
    "Inspire Courage":"buffAllyInspire",
    "Record Action":"buffAllyInspire",
    "Shift Turn Order":"buffAllyInspire",
    "Knowledge Recall":"buffSelfInspire",
    "Omen":"attackRanged",
    "Redirect Curse":"buffAllyGuard",
    "Hex Prolong":"attackRanged",
    "Stabilize":"heal",
    "Nurture":"heal",
    "Revive":"heal",
    "Aura Chant":"buffAllyGuard",
    "Sustained Hymn":"buffAllyInspire",
    "Passive Blessing":"buffAllyGuard",
    "Bargain":"buffSelfInspire",
    "Market Manipulation":"buffSelfInspire",
    "Greed is Good":"buffSelfInspire",
    "Reveal Map":"buffSelfGuard",
    "Alter Terrain":"attackRanged",
    "Pathfinder":"buffSelfInspire",
    "Illusion":"attackRanged",
    "Charm":"attackRanged",
    "Rune Ward":"buffAllyGuard",
    "Explosive Glyph":"attackRanged",
    "Runic Enhancement":"buffAllyGuard",
    "Illusion Stitch":"buffAllyGuard",
    "Armor Weave":"buffAllyGuard",
    "Disguise":"buffSelfGuard",
    "Sea Legs":"buffSelfGuard",
    "Sky Mark":"attackRanged",
    "Trickster Fox":"attackRanged",
    "Owl Sight":"buffSelfGuard",
    "Bear Roar":"attackMelee",
    "Gadget Deploy":"attackRanged",
    "Overclock":"buffSelfInspire",
    "Repair":"heal",
    "Record Heroics":"buffAllyInspire",
    "Echo of Past":"buffAllyInspire",
    "Tale Boost":"buffAllyInspire",
    "Snare":"root",
    "Pitfall":"root",
    "Net Toss":"root",
    "Build Ladder":"buffSelfInspire",
    "Bridge":"buffSelfInspire",
    "Quick Tool":"buffSelfInspire",
    "Swap Positions":"swap",
    "Item Transfer":"buffAllyInspire",
    "Messenger":"buffSelfInspire",
    "Scavenge":"buffSelfInspire",
    "Improvised Weapon":"attackMelee",
    "Salvage Armor":"buffSelfGuard",
    "Flare":"attackRanged",
    "Flag Orders":"buffAllyInspire",
    "Reveal Zone":"buffAllyGuard"
  };

  const RAW_SKILL_DATA = {
    "Taunt":{type:"Command",ep:1,ap:1,range:"2 hex AoE",cooldown:2,effect:"Enemies in range must target the user.",tags:["Morale","Control"]},
    "Shield Wall":{type:"Defensive",ep:1,ap:1,range:"Self + Adjacent",cooldown:3,effect:"+50% CON and prevents knockback.",tags:["Defense"]},
    "Parry":{type:"Defensive",ep:1,ap:1,range:"Melee",cooldown:1,effect:"Negates the next melee hit and counters for half damage.",tags:["Counter"]},
    "Arcane Bolt":{type:"Offensive",ep:1,ap:1,range:"3 hex",cooldown:0,effect:"INT ×1.2 arcane damage.",tags:["Arcane"]},
    "Elemental Blast":{type:"Offensive",ep:1,ap:2,range:"2 hex AoE",cooldown:3,effect:"INT ×1.5 damage with a random element.",tags:["Elemental"]},
    "Ward":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Grants +20% RES.",tags:["Protection"]},
    "Life Leech":{type:"Offensive",ep:1,ap:1,range:"2 hex",cooldown:2,effect:"Deals INT damage and heals half dealt.",tags:["Dark","Sustain"]},
    "Hex":{type:"Debuff",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Reduces STR and DEX by 2 for 2 turns.",tags:["Curse"]},
    "Dark Pact":{type:"Special",ep:1,ap:2,range:"Self",cooldown:4,effect:"Lose 5 HP to gain +2 INT for 2 turns.",tags:["Dark","Pact"]},
    "Snipe":{type:"Offensive",ep:1,ap:2,range:"6 hex",cooldown:2,effect:"Ranged attack that ignores 50% DEF.",tags:["Ranged"]},
    "Volley":{type:"Offensive",ep:1,ap:2,range:"Line 5 hex",cooldown:3,effect:"Line AoE hitting at least 3 targets.",tags:["Ranged","AoE"]},
    "Pinning Shot":{type:"Offensive",ep:1,ap:1,range:"4 hex",cooldown:2,effect:"DEX damage and reduces MOV by 2.",tags:["Control"]},
    "Slipstream Step":{type:"Movement",ep:1,ap:1,range:"Self",cooldown:1,effect:"Move ignoring zones of control.",tags:["Mobility"]},
    "Trap Sense":{type:"Passive",ep:0,ap:0,range:"2 hex",cooldown:0,effect:"Reveals traps within range.",tags:["Detection"]},
    "Ambush":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"Bonus damage if the target hasn’t acted.",tags:["Stealth","Critical"]},
    "Heal":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Restore WIS ×2 HP.",tags:["Holy"]},
    "Turn Undead":{type:"Offensive",ep:1,ap:2,range:"3 hex AoE",cooldown:3,effect:"WIS ×1.5 damage to Undead.",tags:["Holy","Anti-Undead"]},
    "Ward Chant":{type:"Support",ep:1,ap:2,range:"2 hex AoE",cooldown:3,effect:"Allies immune to debuffs for 1 turn.",tags:["Holy","Chant"]},
    "Shapeshift":{type:"Special",ep:1,ap:2,range:"Self",cooldown:5,effect:"Transform into wolf (+DEX) or bear (+STR).",tags:["Nature"]},
    "Entangle":{type:"Control",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Roots the target for 1 turn.",tags:["Nature","Root"]},
    "Restorative Wind":{type:"Healing",ep:1,ap:2,range:"2 hex AoE",cooldown:3,effect:"Heal WIS ×1.2 HP and cure Fatigue.",tags:["Wind"]},
    "Power Strike":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"STR ×1.5 damage with a chance to stagger.",tags:["Physical"]},
    "Counter":{type:"Defensive",ep:1,ap:1,range:"Self",cooldown:1,effect:"Prepare to counter the next melee hit.",tags:["Counter"]},
    "Weapon Stance":{type:"Utility",ep:0,ap:0,range:"Self",cooldown:0,effect:"Toggle between +STR or +DEF stance.",tags:["Stance"]},
    "Backstab":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"Bonus damage when striking from behind.",tags:["Stealth","Critical"]},
    "Poisoned Dagger":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:2,effect:"STR damage and apply Poison for 3 turns.",tags:["Poison"]},
    "Camouflage":{type:"Stealth",ep:1,ap:1,range:"Self",cooldown:3,effect:"Become hidden until an enemy is adjacent.",tags:["Stealth"]},
    "Counterstrike":{type:"Defensive",ep:1,ap:1,range:"Self",cooldown:1,effect:"Reflect 50% melee damage this turn.",tags:["Counter"]},
    "Chi Strike":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"WIS damage and Stun the target.",tags:["Ki"]},
    "Palm of Flame":{type:"Offensive",ep:1,ap:2,range:"Cone",cooldown:3,effect:"Fire cone damage and ignite terrain.",tags:["Fire"]},
    "Totem Call":{type:"Utility",ep:1,ap:2,range:"2 hex",cooldown:5,effect:"Summon a Spirit Totem that projects an aura.",tags:["Spirit"]},
    "Spirit Bind":{type:"Debuff",ep:1,ap:1,range:"3 hex",cooldown:3,effect:"Target loses 1 EP for 1 turn.",tags:["Spirit"]},
    "Stormsong":{type:"Offensive",ep:1,ap:2,range:"3 hex AoE",cooldown:3,effect:"Lightning damage and inflict Shock.",tags:["Storm"]},
    "Zone Control":{type:"Command",ep:1,ap:1,range:"2 hex aura",cooldown:2,effect:"Enemies moving nearby trigger opportunity attacks.",tags:["Control"]},
    "Shield Slam":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:2,effect:"STR damage and Stagger the target.",tags:["Stun"]},
    "Fortify":{type:"Defensive",ep:1,ap:1,range:"Self",cooldown:3,effect:"Increase CON by 30% for 2 turns.",tags:["Defense"]},
    "Deploy Turret":{type:"Utility",ep:1,ap:2,range:"2 hex",cooldown:4,effect:"Summon a turret that deals DEX damage.",tags:["Construct"]},
    "Trap":{type:"Utility",ep:1,ap:1,range:"1 hex",cooldown:3,effect:"Place a snare that roots and damages enemies.",tags:["Trap"]},
    "Salvage Duty":{type:"Utility",ep:0,ap:1,range:"Self",cooldown:0,effect:"Collect salvage for extra loot.",tags:["Resource"]},
    "Raise Skeleton":{type:"Summon",ep:1,ap:2,range:"Adjacent",cooldown:5,effect:"Summon an undead minion.",tags:["Necro"]},
    "Fear":{type:"Debuff",ep:1,ap:1,range:"3 hex AoE",cooldown:3,effect:"Reduce CHA and inflict morale loss.",tags:["Fear"]},
    "Soul Drain":{type:"Offensive",ep:1,ap:1,range:"2 hex",cooldown:2,effect:"INT damage and reduce WIS.",tags:["Dark"]},
    "Shadow Strike":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"DEX + DREAM damage.",tags:["Shadow"]},
    "Harvest Soul":{type:"Offensive",ep:1,ap:2,range:"Melee",cooldown:3,effect:"STR ×1.5 damage and heal equal to damage dealt.",tags:["Dark"]},
    "Fade Step":{type:"Movement",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Teleport to a shadow tile.",tags:["Shadow"]},
    "Harmony Strike":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"STR + CHA damage with bonus if ally nearby.",tags:["Harmony"]},
    "Discordant Wave":{type:"Offensive",ep:1,ap:2,range:"2 hex AoE",cooldown:3,effect:"INT damage and inflict Confuse.",tags:["Chaos"]},
    "Resonance":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Grant +10% damage for 1 turn.",tags:["Song"]},
    "Trick Shot":{type:"Offensive",ep:1,ap:1,range:"4 hex",cooldown:0,effect:"Ricochet to a second target.",tags:["Ranged"]},
    "Ricochet":{type:"Offensive",ep:1,ap:2,range:"Line 3 hex",cooldown:2,effect:"Hit up to three enemies in a line.",tags:["Ranged"]},
    "Quickdraw":{type:"Utility",ep:0,ap:0,range:"Self",cooldown:0,effect:"Always acts first in the round.",tags:["Speed"]},
    "Smoke Vanish":{type:"Stealth",ep:1,ap:1,range:"Self",cooldown:2,effect:"Hidden until next attack.",tags:["Stealth"]},
    "Kunai Throw":{type:"Offensive",ep:1,ap:1,range:"3 hex",cooldown:0,effect:"DEX damage with Bleed on crit.",tags:["Ranged"]},
    "Shadowstep":{type:"Movement",ep:1,ap:1,range:"4 hex",cooldown:2,effect:"Teleport behind enemy and make a free strike.",tags:["Shadow"]},
    "Iaido Strike":{type:"Offensive",ep:1,ap:2,range:"Melee",cooldown:2,effect:"High damage opening strike.",tags:["Duel"]},
    "Discipline Stance":{type:"Utility",ep:0,ap:0,range:"Self",cooldown:0,effect:"Toggle between +DEX or +STR.",tags:["Stance"]},
    "Resolve":{type:"Support",ep:1,ap:1,range:"Self",cooldown:3,effect:"Immune to fear and charm.",tags:["Spirit"]},
    "Disarm":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:2,effect:"Remove target’s weapon for 1 turn.",tags:["Control"]},
    "Broadside":{type:"Offensive",ep:1,ap:2,range:"Line 3 hex",cooldown:3,effect:"STR damage with knockback.",tags:["AoE"]},
    "Rally or Rum":{type:"Support",ep:1,ap:1,range:"2 hex AoE",cooldown:3,effect:"Raise morale and cure Fear.",tags:["Morale"]},
    "Charge":{type:"Offensive",ep:1,ap:2,range:"4 hex line",cooldown:3,effect:"STR ×2 damage and knockback.",tags:["Cavalry"]},
    "Formation Guard":{type:"Defensive",ep:1,ap:1,range:"Adjacent Allies",cooldown:2,effect:"Grant +DEF to adjacent allies.",tags:["Defense"]},
    "Tactical Rally":{type:"Command",ep:1,ap:2,range:"2 hex AoE",cooldown:4,effect:"Allies gain +1 AP this turn.",tags:["Command"]},
    "Boarding Action":{type:"Offensive",ep:1,ap:2,range:"2 hex",cooldown:3,effect:"Leap attack that disorients.",tags:["Pirate"]},
    "Morale Breaker":{type:"Debuff",ep:1,ap:1,range:"2 hex AoE",cooldown:3,effect:"Lower CHA and morale of enemies.",tags:["Morale"]},
    "Naval Tactics":{type:"Passive",ep:0,ap:0,range:"Self",cooldown:0,effect:"Ignore water movement penalties.",tags:["Movement"]},
    "Flameblade":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"Imbue weapon with Fire for 2 turns.",tags:["Fire"]},
    "Arcane Slash":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:2,effect:"INT-based melee attack with knockback.",tags:["Arcane"]},
    "Elemental Guard":{type:"Defensive",ep:1,ap:1,range:"Self",cooldown:3,effect:"Resist Fire, Ice, and Lightning.",tags:["Elemental"]},
    "Tempo Strike":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"STR damage with bonus if Bard/Dancer nearby.",tags:["Rhythm"]},
    "Chant Rally":{type:"Support",ep:1,ap:2,range:"2 hex AoE",cooldown:3,effect:"Boost morale and damage.",tags:["Chant"]},
    "Momentum Slash":{type:"Offensive",ep:1,ap:2,range:"3 hex line",cooldown:3,effect:"Damage scales with attacks this round.",tags:["Combo"]},
    "Alchemy Strike":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:0,effect:"Random elemental damage.",tags:["Alchemy"]},
    "Scrap Bomb":{type:"Offensive",ep:1,ap:2,range:"2 hex AoE",cooldown:3,effect:"AoE blast leaving a Salvage tile.",tags:["Alchemy"]},
    "Essence Burn":{type:"Debuff",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Reduce INT and FAE for 2 turns.",tags:["Alchemy"]},
    "Swap Places":{type:"Utility",ep:1,ap:1,range:"2 hex",cooldown:2,effect:"Swap position with an ally.",tags:["Position"]},
    "Intercept":{type:"Defensive",ep:1,ap:1,range:"2 hex",cooldown:2,effect:"Take damage for an ally.",tags:["Guard"]},
    "Silent Guard":{type:"Stealth",ep:1,ap:1,range:"Self",cooldown:3,effect:"Become hidden and gain DEF.",tags:["Stealth"]},
    "Ignite":{type:"Offensive",ep:1,ap:1,range:"2 hex",cooldown:2,effect:"Fire damage and apply Burn.",tags:["Fire"]},
    "Reveal Shadows":{type:"Utility",ep:0,ap:0,range:"3 hex AoE",cooldown:0,effect:"Reveal hidden units.",tags:["Reveal"]},
    "Firebrand":{type:"Offensive",ep:1,ap:2,range:"Cone",cooldown:3,effect:"Fire cone AoE igniting terrain.",tags:["Fire"]},
    "Parry-Riposte":{type:"Offensive",ep:1,ap:1,range:"Melee",cooldown:1,effect:"Block an attack and strike back immediately.",tags:["Duel"]},
    "Showboat":{type:"Support",ep:0,ap:1,range:"Self",cooldown:3,effect:"Boost morale and lower nearby enemy morale.",tags:["Performance"]},
    "Teleport Rift":{type:"Movement",ep:1,ap:2,range:"5 hex",cooldown:3,effect:"Teleport an ally or self.",tags:["Rift"]},
    "Banish":{type:"Control",ep:1,ap:2,range:"3 hex",cooldown:3,effect:"Remove a target from the field for 1 turn.",tags:["Rift"]},
    "Anchor Zone":{type:"Defensive",ep:1,ap:1,range:"2 hex AoE",cooldown:4,effect:"Blocks teleport and blink effects in the zone.",tags:["Rift"]},
    "Inspiring Ballad":{type:"Support",ep:1,ap:1,range:"2 hex AoE",cooldown:3,effect:"Allies gain +15% damage for 2 turns.",tags:["Song","Morale"]},
    "Cleansing Chorus":{type:"Support",ep:1,ap:2,range:"2 hex AoE",cooldown:3,effect:"Heal WIS ×1.2 HP and cleanse 1 debuff.",tags:["Song","Cleanse"]},
    "Battle Hymn":{type:"Support",ep:1,ap:2,range:"2 hex AoE",cooldown:4,effect:"Grant allies +1 AP for the next turn.",tags:["Song","Rally"]},
    "Mirrorstep":{type:"Movement",ep:1,ap:1,range:"3 hex",cooldown:1,effect:"Blink to an empty tile and gain Evasion.",tags:["Dance"]},
    "Dodge Dance":{type:"Defensive",ep:1,ap:1,range:"Self",cooldown:2,effect:"Gain +30% DEX and Dodge chance for 1 turn.",tags:["Dance"]},
    "Action Gift":{type:"Support",ep:1,ap:2,range:"Adjacent Ally",cooldown:3,effect:"Target ally gains 1 bonus action.",tags:["Dance","Rally"]},
    "Parley":{type:"Utility",ep:1,ap:1,range:"3 hex",cooldown:3,effect:"Attempt to pacify enemies, lowering CHA attacks.",tags:["Diplomacy"]},
    "Influence Morale":{type:"Support",ep:1,ap:1,range:"2 hex AoE",cooldown:3,effect:"Raise ally morale and lower enemy morale.",tags:["Diplomacy"]},
    "Truce":{type:"Control",ep:1,ap:2,range:"3 hex",cooldown:4,effect:"Target enemy cannot attack this round.",tags:["Diplomacy"]},
    "Command Authority":{type:"Command",ep:1,ap:1,range:"2 hex AoE",cooldown:2,effect:"Allies gain +10% DEF and STR.",tags:["Leadership"]},
    "Deploy Orders":{type:"Command",ep:1,ap:2,range:"3 hex",cooldown:3,effect:"Direct an ally to immediately reposition 2 hex.",tags:["Leadership"]},
    "Rallying Cry":{type:"Command",ep:1,ap:2,range:"3 hex AoE",cooldown:4,effect:"Allies gain +1 AP and morale.",tags:["Leadership"]},
    "Supply Drop":{type:"Support",ep:1,ap:2,range:"4 hex",cooldown:3,effect:"Throw supplies that restore 10 HP and 1 EP.",tags:["Logistics"]},
    "Stamina Boost":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Target gains +1 AP this round.",tags:["Logistics"]},
    "Resupply":{type:"Support",ep:1,ap:2,range:"3 hex AoE",cooldown:4,effect:"Restore 1 EP to allies in range.",tags:["Logistics"]},
    "Reveal Weakness":{type:"Debuff",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Reduce target DEF by 20% for 2 turns.",tags:["Scan"]},
    "Lore Archive":{type:"Utility",ep:0,ap:1,range:"Self",cooldown:0,effect:"Store knowledge to gain +INT next analysis.",tags:["Archive"]},
    "Battle Scan":{type:"Utility",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Reveal target stats and resistances.",tags:["Scan"]},
    "Summon Beast":{type:"Summon",ep:1,ap:2,range:"Adjacent",cooldown:4,effect:"Call a companion beast to fight for you.",tags:["Beast"]},
    "Command Beast":{type:"Command",ep:1,ap:1,range:"3 hex",cooldown:1,effect:"Order a beast ally to act immediately.",tags:["Beast"]},
    "Wild Roar":{type:"Debuff",ep:1,ap:1,range:"2 hex AoE",cooldown:3,effect:"Frighten enemies reducing their morale.",tags:["Beast"]},
    "Herbal Remedy":{type:"Healing",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Heal WIS ×1.5 HP over 2 turns.",tags:["Herbal"]},
    "Poison Bomb":{type:"Offensive",ep:1,ap:2,range:"2 hex AoE",cooldown:3,effect:"Deal damage and apply Poison for 2 turns.",tags:["Poison"]},
    "Antidote":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Cure Poison and grant resistance.",tags:["Herbal"]},
    "Prophecy":{type:"Support",ep:1,ap:1,range:"3 hex",cooldown:3,effect:"Ally gains +20% crit chance for 2 turns.",tags:["Divination"]},
    "Veil Sight":{type:"Utility",ep:1,ap:1,range:"Self",cooldown:2,effect:"See invisible units and traps for 2 turns.",tags:["Divination"]},
    "Fate Bind":{type:"Control",ep:1,ap:2,range:"3 hex",cooldown:3,effect:"Link target to share damage with caster.",tags:["Divination"]},
    "Sacred Ward":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Grant +25% RES for 2 turns.",tags:["Holy"]},
    "Blessing":{type:"Support",ep:1,ap:1,range:"2 hex AoE",cooldown:3,effect:"Allies gain +10% to all stats for 1 turn.",tags:["Holy"]},
    "Inspire Courage":{type:"Support",ep:1,ap:1,range:"2 hex AoE",cooldown:3,effect:"Allies gain morale and immunity to fear.",tags:["Holy"]},
    "Record Action":{type:"Utility",ep:0,ap:1,range:"Self",cooldown:1,effect:"Copy an ally action for later reuse.",tags:["Archive"]},
    "Shift Turn Order":{type:"Command",ep:1,ap:2,range:"2 hex",cooldown:3,effect:"Swap two allies in the initiative order.",tags:["Archive"]},
    "Knowledge Recall":{type:"Support",ep:0,ap:1,range:"Self",cooldown:1,effect:"Gain +2 INT for the next skill used.",tags:["Archive"]},
    "Omen":{type:"Debuff",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Inflict Doom causing extra damage next hit.",tags:["Fate"]},
    "Redirect Curse":{type:"Support",ep:1,ap:1,range:"3 hex",cooldown:3,effect:"Move a debuff from ally to enemy.",tags:["Fate"]},
    "Hex Prolong":{type:"Debuff",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Extend duration of debuffs on target.",tags:["Fate"]},
    "Stabilize":{type:"Healing",ep:1,ap:1,range:"Adjacent Ally",cooldown:1,effect:"Prevent target from dropping below 1 HP this turn.",tags:["Care"]},
    "Nurture":{type:"Healing",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Regenerate WIS ×1 HP for 3 turns.",tags:["Care"]},
    "Revive":{type:"Healing",ep:1,ap:2,range:"Adjacent Ally",cooldown:4,effect:"Revive a downed ally at 30% HP.",tags:["Care"]},
    "Aura Chant":{type:"Support",ep:1,ap:1,range:"2 hex AoE",cooldown:2,effect:"Project an aura granting +DEF.",tags:["Chant"]},
    "Sustained Hymn":{type:"Support",ep:1,ap:2,range:"Self",cooldown:3,effect:"Maintain a hymn restoring 1 EP to allies nearby.",tags:["Chant"]},
    "Passive Blessing":{type:"Support",ep:0,ap:0,range:"Self Aura",cooldown:0,effect:"Allies adjacent gain +5% all resistances.",tags:["Chant"]},
    "Bargain":{type:"Utility",ep:0,ap:1,range:"Self",cooldown:1,effect:"Gain extra loot and discount on shop actions.",tags:["Trade"]},
    "Market Manipulation":{type:"Utility",ep:1,ap:1,range:"3 hex",cooldown:3,effect:"Alter prices and morale of nearby foes.",tags:["Trade"]},
    "Greed is Good":{type:"Support",ep:0,ap:1,range:"Self",cooldown:2,effect:"Convert 5 HP into +2 AP this turn.",tags:["Trade"]},
    "Reveal Map":{type:"Utility",ep:1,ap:1,range:"Global",cooldown:4,effect:"Uncover hidden tiles and enemies on the map.",tags:["Survey"]},
    "Alter Terrain":{type:"Control",ep:1,ap:2,range:"3 hex",cooldown:4,effect:"Change terrain tile to difficult ground.",tags:["Survey"]},
    "Pathfinder":{type:"Support",ep:1,ap:1,range:"Self",cooldown:2,effect:"Ignore terrain penalties for 2 turns.",tags:["Survey"]},
    "Illusion":{type:"Control",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Create a decoy that draws enemy attacks.",tags:["Hex"]},
    "Charm":{type:"Control",ep:1,ap:2,range:"3 hex",cooldown:3,effect:"Force target to act on your behalf for 1 turn.",tags:["Hex"]},
    "Rune Ward":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Grant +30% resistance to elemental damage.",tags:["Rune"]},
    "Explosive Glyph":{type:"Offensive",ep:1,ap:2,range:"2 hex",cooldown:3,effect:"Place a glyph that explodes next round.",tags:["Rune"]},
    "Runic Enhancement":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:3,effect:"Imbue ally weapon for +20% damage.",tags:["Rune"]},
    "Illusion Stitch":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Grant ally a disguise increasing DEF.",tags:["Tailor"]},
    "Armor Weave":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:3,effect:"Increase CON by 15% for 2 turns.",tags:["Tailor"]},
    "Disguise":{type:"Utility",ep:1,ap:1,range:"Self",cooldown:3,effect:"Become disguised reducing enemy targeting.",tags:["Tailor"]},
    "Sea Legs":{type:"Support",ep:0,ap:1,range:"Self",cooldown:2,effect:"Ignore water hazards and gain stability.",tags:["Navigation"]},
    "Sky Mark":{type:"Offensive",ep:1,ap:1,range:"5 hex",cooldown:2,effect:"Mark a target granting bonus ranged damage.",tags:["Navigation"]},
    "Trickster Fox":{type:"Utility",ep:0,ap:1,range:"Self",cooldown:2,effect:"Gain +DEX and create a decoy trail.",tags:["Beast"]},
    "Owl Sight":{type:"Utility",ep:0,ap:1,range:"Self",cooldown:2,effect:"Gain night vision and reveal hidden units.",tags:["Beast"]},
    "Bear Roar":{type:"Offensive",ep:1,ap:1,range:"Cone",cooldown:3,effect:"Deal damage and taunt enemies in front.",tags:["Beast"]},
    "Gadget Deploy":{type:"Utility",ep:1,ap:2,range:"2 hex",cooldown:3,effect:"Deploy a gadget with random helpful effect.",tags:["Tech"]},
    "Overclock":{type:"Support",ep:1,ap:1,range:"Self",cooldown:2,effect:"Increase AP by 1 but take 5 damage.",tags:["Tech"]},
    "Repair":{type:"Support",ep:1,ap:1,range:"Adjacent Ally",cooldown:2,effect:"Restore 15 HP to mechanical allies or 10 HP otherwise.",tags:["Tech"]},
    "Record Heroics":{type:"Support",ep:0,ap:1,range:"2 hex",cooldown:2,effect:"Grant ally +10% damage when recounted.",tags:["Story"]},
    "Echo of Past":{type:"Support",ep:1,ap:2,range:"3 hex",cooldown:3,effect:"Repeat the last supportive action used.",tags:["Story"]},
    "Tale Boost":{type:"Support",ep:0,ap:1,range:"2 hex",cooldown:2,effect:"Allies gain +CHA for morale checks.",tags:["Story"]},
    "Snare":{type:"Control",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Root a target for 1 turn.",tags:["Trap"]},
    "Pitfall":{type:"Control",ep:1,ap:2,range:"1 hex",cooldown:3,effect:"Create a pit causing damage and root on trigger.",tags:["Trap"]},
    "Net Toss":{type:"Control",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Immobilize target for 1 turn.",tags:["Trap"]},
    "Build Ladder":{type:"Utility",ep:1,ap:1,range:"Adjacent",cooldown:2,effect:"Create climbable terrain.",tags:["Construct"]},
    "Bridge":{type:"Utility",ep:1,ap:2,range:"2 hex",cooldown:3,effect:"Create a temporary bridge over hazards.",tags:["Construct"]},
    "Quick Tool":{type:"Utility",ep:0,ap:1,range:"Self",cooldown:1,effect:"Gain +1 AP when interacting with objects.",tags:["Construct"]},
    "Swap Positions":{type:"Utility",ep:1,ap:1,range:"3 hex",cooldown:2,effect:"Swap positions of two allies.",tags:["Logistics"]},
    "Item Transfer":{type:"Utility",ep:0,ap:1,range:"Adjacent Ally",cooldown:0,effect:"Give an item and grant +1 AP.",tags:["Logistics"]},
    "Messenger":{type:"Movement",ep:0,ap:1,range:"Self",cooldown:1,effect:"Gain +2 MOV for the round.",tags:["Logistics"]},
    "Scavenge":{type:"Utility",ep:0,ap:1,range:"Self",cooldown:1,effect:"Recover materials granting +1 EP next turn.",tags:["Salvage"]},
    "Improvised Weapon":{type:"Offensive",ep:0,ap:1,range:"Melee",cooldown:0,effect:"Deal STR damage with found objects.",tags:["Salvage"]},
    "Salvage Armor":{type:"Defensive",ep:0,ap:1,range:"Self",cooldown:2,effect:"Gain +20% DEF for 2 turns.",tags:["Salvage"]},
    "Flare":{type:"Utility",ep:1,ap:1,range:"5 hex",cooldown:2,effect:"Reveal a zone and remove stealth.",tags:["Signal"]},
    "Flag Orders":{type:"Command",ep:1,ap:1,range:"3 hex AoE",cooldown:2,effect:"Allies follow orders gaining +SPD.",tags:["Signal"]},
    "Reveal Zone":{type:"Utility",ep:1,ap:1,range:"3 hex AoE",cooldown:3,effect:"Highlight hidden traps and foes.",tags:["Signal"]}
  };

  function deriveRangeValue(text){
    if(!text) return undefined;
    const str = String(text).toLowerCase();
    if(str.includes('self') && str.includes('adjacent')) return 1;
    if(str.includes('self')) return 0;
    if(str.includes('adjacent')) return 1;
    if(str.includes('melee')) return 1;
    if(str.includes('cone')) return 2;
    const match = str.match(/(\d+)/);
    if(match) return Number(match[1]);
    if(str.includes('line')) return 3;
    return undefined;
  }

  const SKILL_DATA = Object.fromEntries(Object.entries(RAW_SKILL_DATA).map(([name,data])=>[
    name,
    {
      ...data,
      rangeValue: deriveRangeValue(data.range)
    }
  ]));

  const DEFAULT_NAME_OVERRIDES = {
    Knight:"Tallis (Knight)",
    Archer:"Clover (Archer)"
  };

  const GLYPH_OVERRIDES = {
    Knight:"⚔",
    Magician:"✨",
    Warlock:"☠",
    Archer:"🏹",
    Scout:"🧭",
    Cleric:"✚",
    Druid:"🌿",
    Fighter:"🥊",
    Rogue:"🗡",
    Monk:"🙏",
    Shaman:"🌀",
    Warden:"🛡",
    Engineer:"⚙",
    Necromancer:"💀",
    Reaper:"⚰",
    Symphonist:"🎵",
    Gunslinger:"🔫",
    Ninja:"🥷",
    Samurai:"🥋",
    Pirate:"🏴‍☠️",
    Brigadier:"🎖",
    Privateer:"⚓",
    Spellblade:"✨",
    Skaldblade:"🪕",
    Essentier:"⚗️",
    Shadowguard:"🌑",
    Torchbearer:"🔥",
    Swashbuckler:"🏴",
    Riftwarden:"🌌"
    ,Bard:"🎼"
    ,Dancer:"💃"
    ,Diplomat:"🤝"
    ,Commander:"🪖"
    ,Quartermaster:"📦"
    ,Librarian:"📚"
    ,Beastmaster:"🐾"
    ,Herbalist:"🌼"
    ,Oracle:"🔮"
    ,Chaplain:"🕊"
    ,Archivist:"🗂"
    ,Soothsayer:"🔭"
    ,Caretaker:"🩺"
    ,Chanter:"🎤"
    ,Merchant:"💰"
    ,Cartographer:"🗺"
    ,Witch:"🧙"
    ,Runesmith:"🪨"
    ,Tailor:"🧵"
    ,Navigator:"🧭"
    ,FolkCompanion:"🐕"
    ,Artificer:"🛠"
    ,Chronicler:"📝"
    ,Trapper:"🪤"
    ,Tinker:"🔧"
    ,Courier:"📯"
    ,Scrapper:"🪓"
    ,Signalist:"🚩"
  };

  function skillKey(name){
    return name
      .split(/[^a-zA-Z0-9]+/)
      .filter(Boolean)
      .map(part=>part.charAt(0).toUpperCase()+part.slice(1).toLowerCase())
      .join('');
  }

  function defaultNameFor(name){
    return DEFAULT_NAME_OVERRIDES[name] || name;
  }

  function inferRange(entry){
    const rangedRegex = /(Shot|Throw|Bolt|Blast|Gun|Rift|Banish|Kunai|Ricochet|Quickdraw|Broadside|Volley|Snipe|Song|Wave|Wind|Bomb|Ignite|Essence|Spirit|Storm|Anchor|Teleport)/i;
    if(entry.startingSkills.some(skill=>rangedRegex.test(skill))) return 3;
    if(/Magician|Warlock|Cleric|Druid|Shaman|Necromancer|Reaper|Symphonist|Gunslinger|Ninja|Spellblade|Torchbearer|Riftwarden|Engineer|Archer|Scout|Privateer|Pirate|Bard|Dancer|Commander|Quartermaster|Librarian|Beastmaster|Herbalist|Oracle|Chaplain|Archivist|Soothsayer|Caretaker|Chanter|Merchant|Cartographer|Witch|Runesmith|Tailor|Navigator|Folk\sCompanion|Artificer|Chronicler|Trapper|Tinker|Courier|Scrapper|Signalist/i.test(entry.name)) return 3;
    if(entry.stats.DEX >= 8 || entry.stats.INT >= 7) return 2;
    return 1;
  }

  function computeDerivedStats(entry){
    const { stats, resources, attunement } = entry;
    const maxHp = Math.max(18, Math.round((resources.HP || 20) * 1.5));
    const atk = Math.max(6, Math.round(4 + stats.STR*0.9 + stats.INT*0.45 + stats.DEX*0.35));
    const def = Math.max(4, Math.round(2 + stats.CON*0.9 + stats.WIS*0.35));
    const dream = attunement && typeof attunement.DREAM === 'number' ? attunement.DREAM : 0;
    const spd = Math.max(5, Math.round(3 + stats.DEX*1.05 + dream*0.35));
    const range = inferRange(entry);
    return { maxHp, atk, def, spd, range };
  }

  global.FABLE_DATA = {
    CLASS_DATABASE,
    SKILL_BEHAVIORS,
    SKILL_DATA,
    GLYPH_OVERRIDES,
    defaultNameFor,
    skillKey,
    inferRange,
    computeDerivedStats
  };
})(window);
